# Generated by Django 4.0.1 on 2022-04-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/account.png', upload_to='media/img/'),
        ),
    ]
