# Generated by Django 4.0.2 on 2022-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0006_rename_lastname_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='star_user',
            field=models.ManyToManyField(to='myProfile.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/icons8-account-48.png', upload_to='media/img/'),
        ),
    ]
