# Generated by Django 4.0.2 on 2022-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
