# Generated by Django 4.0.1 on 2022-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.CharField(max_length=200, null=True, verbose_name='to User'),
        ),
    ]
