# Generated by Django 4.0.1 on 2022-04-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
