# Generated by Django 4.0.4 on 2022-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0006_rename_lastname_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/icons8-account-48.png', upload_to='media/img/'),
        ),
    ]
